### ISSUE TITLE
STANAG Transforms must return byte[]

### ISSUE THREAD

**Issue by frizman21** [albersgroup/picante#26]
See modifications necessary in this commit.
https://github.com/albersgroup/picante/pull/25/commits/ab5de7a61bdad86deaac2e939573f54d44664ba5

- [x] update groovy script to match existing JSON message format in the typeMetaInfo
- [x] update groovy script to suck out the STANAG message number. This means we are diverging from the RTI DDS version of this groovy script. Create a copy and put it in this module.
- [x] add option messageLength to the MessageType enumeration.
- [x] populate these values for all the messageTypes that we have already implemented.
- [x] update the template to include it, in addition to the byte[] changes and the addition of the try/catch block.

**Comment by frizman21** [comment]
@jasoncpace , this is something else you might be able to knock out quickly

**Comment by frizman21** [comment]
The latest code gen needs two more inputs. We need to come up with an approach. 
Both should be included in the json output from the Groovy script.
The M41 can be derived from the message type name ("M00041_Pascal_Case_Name")
The message length... we eventually want to derive from the message definition. Today, it's hard-coded in the transport. What to do...?

```
MessageWrapper wrapper = Stanag4586Helper.getWrapper(typ, MessageType.M41);
wrapper.setMessageLength(40);
```

**Comment by Reliquia33ad** [comment]
With messageId now added to the json file output, we could leverage lookups against MessageType.java to pull class name information to create the transform name.   Instead of pulling it from the json itself.

**Comment by Reliquia33ad** [comment]
Regarding " update groovy script to match existing JSON message format in the typeMetaInfo" item.   Since we do not have access to the Java class names at the time the groovy script is running, the extract saves them by the name of the object in Cameo (M0.....Message_Name.json).   When VelocityStartGenerator.java is executed, the messageTypeId is used to look up the package/class for creating the transform.   Supporting messageTypeId as a member variable in copperfield/.../primitives/MessageType.java was a necessary enhancement.

**Comment by Reliquia33ad** [comment]
Looking back.  This probably could have been done without the changes to the groovy script and primitive types.  Extracting message number could have been handled in the Generator code..  This implementation, however, positions the code for supporting future features in addition to solving this issue.
